name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-release:
    name: Build Release Bundles (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install Node dependencies
        run: npm ci

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: build
          # 可在此添加签名或发布参数 (sign, identifier 等)

      # cargo-deny step removed (quality checks disabled)

      - name: Upload Bundles Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-bundles-${{ runner.os }}
          path: src-tauri/target/release/bundle

  publish-release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build-release

    steps:
      - name: Download MacOS bundle
        uses: actions/download-artifact@v4
        with:
          name: tauri-bundles-macos-latest
          path: bundles/macos

      - name: Download Linux bundle
        uses: actions/download-artifact@v4
        with:
          name: tauri-bundles-ubuntu-latest
          path: bundles/linux

      - name: Download Windows bundle
        uses: actions/download-artifact@v4
        with:
          name: tauri-bundles-windows-latest
          path: bundles/windows

      - name: Generate Release Notes and Checksums
        run: |
          echo "## Release Assets" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "- macOS bundles in bundles/macos" >> RELEASE_NOTES.md
          echo "- Linux bundles in bundles/linux" >> RELEASE_NOTES.md
          echo "- Windows bundles in bundles/windows" >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## SHA256 Checksums" >> RELEASE_NOTES.md
          find bundles -type f -maxdepth 3 -print0 | xargs -0 shasum -a 256 > SHA256SUMS.txt
          head -n 50 SHA256SUMS.txt >> RELEASE_NOTES.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
          generate_release_notes: true
          body_path: RELEASE_NOTES.md
          files: |
            bundles/macos/**/*
            bundles/linux/**/*
            bundles/windows/**/*
            SHA256SUMS.txt
