name: Release

on:
  push:
    tags:
      - "[0-9]*.*.*"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "22"
  RUST_BACKTRACE: short
  CARGO_INCREMENTAL: 0
  # Faster compile (trade a little optimization time for speed)
  CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 256
  CARGO_PROFILE_RELEASE_LTO: "false"

jobs:
  prepare:
    name: Prepare (Frontend + Changelog)
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    outputs:
      changelog: ${{ steps.changelog.outputs.content }}
      previous_tag: ${{ steps.previous_tag.outputs.tag }}
    steps:
      - name: Checkout (full history for tags/changelog)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Compute pnpm store path
        id: pnpm-store
        shell: bash
        run: |
          STORE_PATH=$(pnpm store path --silent 2>/dev/null || echo "")
          if [ -z "$STORE_PATH" ]; then
            # Fallback to default pnpm store location based on OS
            if [ "$RUNNER_OS" = "Windows" ]; then
              STORE_PATH="$LOCALAPPDATA/pnpm/store"
            elif [ "$RUNNER_OS" = "macOS" ]; then
              STORE_PATH="$HOME/Library/pnpm/store"
            else
              STORE_PATH="$HOME/.local/share/pnpm/store"
            fi
          fi
          echo "STORE_PATH=$STORE_PATH" >> $GITHUB_ENV
          echo "Computed pnpm store path: $STORE_PATH"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-${{ runner.arch }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build frontend (single build for all targets)
        run: pnpm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist
          retention-days: 3

      - name: Get previous tag
        id: previous_tag
        shell: bash
        run: |
          PREVIOUS_TAG=$(git tag --sort=-v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | grep -v "${{ github.ref_name }}" | head -n 1)
          echo "tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
          echo "Previous tag: $PREVIOUS_TAG"

      - name: Extract changelog
        id: changelog
        shell: bash
        run: |
          # Extract changelog for current version (without square brackets)
          CHANGELOG=$(sed -n "/^## ${{ github.ref_name }}/,/^## /p" CHANGELOG.md | sed '1d;$d' | sed '/^$/d')
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="请查看完整的更新日志: [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)"
          fi
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  bundle:
    name: Bundle (${{ matrix.platform }})
    needs: prepare
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "Windows (x64)"
            os: windows-latest
          - platform: "Windows (ARM64)"
            os: windows-11-arm
          - platform: "macOS (Apple Silicon)"
            os: macos-latest
          - platform: "macOS (Intel)"
            os: macos-15-intel
          - platform: "Ubuntu (x64)"
            os: ubuntu-24.04
          - platform: "Ubuntu (ARM64)"
            os: ubuntu-24.04-arm

    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Download frontend dist
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Compute pnpm store path
        id: pnpm-store
        shell: bash
        run: |
          STORE_PATH=$(pnpm store path --silent 2>/dev/null || echo "")
          if [ -z "$STORE_PATH" ]; then
            # Fallback to default pnpm store location based on OS
            if [ "$RUNNER_OS" = "Windows" ]; then
              STORE_PATH="$LOCALAPPDATA/pnpm/store"
            elif [ "$RUNNER_OS" = "macOS" ]; then
              STORE_PATH="$HOME/Library/pnpm/store"
            else
              STORE_PATH="$HOME/.local/share/pnpm/store"
            fi
          fi
          echo "STORE_PATH=$STORE_PATH" >> $GITHUB_ENV
          echo "Computed pnpm store path: $STORE_PATH"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-${{ runner.arch }}-

      - name: Install dependencies (no rebuild)
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            xdg-utils

      - name: Install x86_64 OpenSSL (macOS Intel only)
        if: matrix.os == 'macos-15-intel'
        run: |
          arch -x86_64 brew install openssl@3
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Patch tauri.conf.json (skip beforeBuildCommand)
        shell: bash
        run: |
          # Temporarily clear beforeBuildCommand to skip frontend rebuild
          if command -v jq &> /dev/null; then
            jq '.build.beforeBuildCommand = ""' src-tauri/tauri.conf.json > src-tauri/tauri.conf.json.tmp
            mv src-tauri/tauri.conf.json.tmp src-tauri/tauri.conf.json
          else
            # Fallback: use sed if jq not available
            sed -i.bak 's/"beforeBuildCommand"[[:space:]]*:[[:space:]]*"[^"]*"/"beforeBuildCommand": ""/' src-tauri/tauri.conf.json
          fi
          echo "Patched tauri.conf.json"

      - name: Build Tauri app (skip frontend build)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Don't create GitHub Release here (done in release job)
          # tagName: ${{ github.ref_name }}  # Omit to avoid auto-release
          includeRelease: true
          includeUpdaterJson: false
          tauriScript: pnpm tauri

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/rpm/*.rpm
            src-tauri/target/release/bundle/appimage/*.AppImage
          retention-days: 7

  release:
    name: Create Release (Attach All Artifacts)
    needs: [prepare, bundle]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for tag context)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Download all bundle artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_assets
          pattern: bundle-*
          merge-multiple: true

      - name: List downloaded files (debug)
        shell: bash
        run: |
          echo "Downloaded files:"
          find release_assets -type f || ls -R release_assets

      - name: Generate release body (envsubst template)
        shell: bash
        run: |
          export VERSION="${{ github.ref_name }}"
          export REPOSITORY="${{ github.repository }}"
          export CHANGELOG="${{ needs.prepare.outputs.changelog }}"
          export PREVIOUS_TAG="${{ needs.prepare.outputs.previous_tag }}"
          if [ -n "$PREVIOUS_TAG" ]; then
            export COMPARE_LINK="[${PREVIOUS_TAG}...${VERSION}](https://github.com/${REPOSITORY}/compare/${PREVIOUS_TAG}...${VERSION})"
          else
            export COMPARE_LINK="[查看提交历史](https://github.com/${REPOSITORY}/commits/${VERSION})"
          fi
          envsubst < .github/release_body_template.md > release_body.md
          echo "Generated release_body.md preview (first 60 lines):"
          sed -n '1,60p' release_body.md

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: "Bing Wallpaper Now ${{ github.ref_name }}"
          draft: false
          prerelease: false
          make_latest: true
          files: |
            release_assets/**/*.exe
            release_assets/**/*.msi
            release_assets/**/*.dmg
            release_assets/**/*.deb
            release_assets/**/*.rpm
            release_assets/**/*.AppImage
          body_path: release_body.md
